name: "TwinCAT Build Action"
description: "Custom action"
inputs:
  targetNetId:
    description: "NetId of target"
    required: true
  targetPlatform:
    description: "Target CPU architecture"
    required: true
  vsShell:
    description: "Visual Studio shell version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell : powershell
      env:
        #SolutionPath: ${{ inputs.solutionPath }}
        TargetNetId: ${{ inputs.targetNetId }}
        TargetPlatform: ${{ inputs.targetPlatform }}
        VSShell: ${{ inputs.vsShell }}

    - name: Run build script
        run: |
          powershell -File ${{ github.action_path }}/scripts/tc3-build-script.ps1
