name: "TwinCAT Build Action"
description: "Builds a TwinCAT solution from the checked out repo."
inputs:
  solution-path:
    description: "Solution file path"
    required: true
  target-net-id:
    description: "NetId of target"
    required: true
  target-platform:
    description: "Target CPU architecture"
    required: true
  vs-shell:
    description: "Visual Studio shell version"
    required: true
  display-ui:
    description: "Display Visual Studio UI"
    required: false
    default: '$false'
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell : powershell
      run: |
        echo "SOLUTION_PATH=${{ inputs.solution-path }}" >> $env:GITHUB_ENV
        echo "TARGET_NETID=${{ inputs.target-net-id }}" >> $env:GITHUB_ENV
        echo "TARGET_PLATFORM=$(${{ inputs.target-platform }})" >> $env:GITHUB_ENV
        echo "VS_SHELL=${{ inputs.vs-shell }}" >> $env:GITHUB_ENV
        echo "VS_UI=${{ inputs.display-ui }}" >> $env:GITHUB_ENV
                   
    - name: Run build script
      shell: powershell
      run: |
        powershell -File ${{ github.action_path }}/scripts/tc3-build-script.ps1
