name: "TwinCAT Build Action"
description: "Builds a TwinCAT solution from the checked out repo."
inputs:
  target-net-id:
    description: "NetId of target"
    required: true
  target-platform:
    description: "Target CPU architecture"
    required: true
  vs-shell:
    description: "Visual Studio shell version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell : powershell
      run: |
        echo "TargetNetId=$(${{ inputs.target-net-id }} >> $GITHUB_ENV)"
        echo "TargetPlatform=$(${{ inputs.target-platform }}" >> $GITHUB_ENV)"
        echo "VSShell=$(${{ inputs.vs-shell }}" >> $GITHUB_ENV)"
      
    - name: Run build script
        shell: powershell
        run: |
          powershell -File ${{ github.action_path }}/scripts/tc3-build-script.ps1
