name: "TwinCAT Build Action"
description: "Builds a TwinCAT solution from the checked out repo."
inputs:
  targetNetId:
    description: "NetId of target"
    required: true
  targetPlatform:
    description: "Target CPU architecture"
    required: true
  vsShell:
    description: "Visual Studio shell version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell : powershell
      run: |
        echo "TargetNetId=${{ inputs.targetNetId }}" >> $GITHUB_ENV
        echo "TargetPlatform=${{ inputs.targetPlatform }}" >> $GITHUB_ENV
        echo "VSShell=${{ inputs.vsShell }}" >> $GITHUB_ENV
      
    - name: Run build script
        shell: powershell
        run: |
          powershell -File ${{ github.action_path }}/scripts/tc3-build-script.ps1
