name: "TwinCAT Build Action"
description: "Custom action"
inputs:
  targetNetId:
    description: "NetId of target"
    required: true
runs:
  using: "composite"
  steps:
    - run: powershell -File ${{ github.action_path }}/scripts/tc3-build-script.ps1 ${{ inputs.targetNetId }}
      shell: powershell
