name: 'TwinCAT Build Action'
description: 'Custom action'
inputs:
  targetNetId:
    description: 'NetId of target'
    required: true
    default: '192.168.4.1.1.1'
runs:
  using: 'composite'
  steps:
    - shell: powershell
      run: |
        -File ${{ github.action_path }}/scripts/tc3-build-script.ps1
