name: Test Action

on:
  #push:
  #  branches:
  #   - main
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-action-job:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build script
        uses: ./
        with:
          solution-path: ${{ github.workspace }}
          target-net-id: '192.168.4.1.1.1'
          target-platform: '"TwinCAT RT (x64)"' # double quotes sent as part of the string to stop string being split on spaces
          vs-shell: "TcXaeShell.DTE.15.0"
          vs-silent: "$true"
